package org.confluence.music.common.init;

import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import org.confluence.lib.common.component.ModRarity;
import org.confluence.lib.common.item.CustomRarityItem;
import org.confluence.music.ConfluenceMusic;

public final class CMItems {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(ConfluenceMusic.MODID);

    public static final DeferredItem<CustomRarityItem> ALPHA = ITEMS.register("alpha", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.ALPHA), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLD = ITEMS.register("otherworld", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.NEW_JOURNEY), ModRarity.EXPERT));
    

    public static final DeferredItem<CustomRarityItem> OVERWORLD_DAY = ITEMS.register("overworld_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OVERWORLD_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> ALT_OVERWORLD_DAY = ITEMS.register("alt_overworld_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.ALT_OVERWORLD_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OVERWORLD_NIGHT = ITEMS.register("overworld_night", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OVERWORLD_NIGHT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> JOURNEYS_BEGINNING = ITEMS.register("journeys_beginning", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.JOURNEYS_BEGINNING), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> JOURNEYS_END = ITEMS.register("journeys_end", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.JOURNEYS_END), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> TITLE = ITEMS.register("title", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.TITLE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> ALT_TITLE = ITEMS.register("alt_title", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.ALT_TITLE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> DAY_REMIX = ITEMS.register("day_remix", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.DAY_REMIX), ModRarity.EXPERT));

    public static final DeferredItem<CustomRarityItem> SNOW = ITEMS.register("snow", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.SNOW), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> ICE = ITEMS.register("ice", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.ICE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND_ICE = ITEMS.register("underground_ice", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND_ICE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> DESERT = ITEMS.register("desert", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.DESERT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND_DESERT = ITEMS.register("underground_desert", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND_DESERT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OCEAN_DAY = ITEMS.register("ocean_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OCEAN_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OCEAN_NIGHT = ITEMS.register("ocean_night", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OCEAN_NIGHT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> SPACE_DAY = ITEMS.register("space_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.SPACE_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> SPACE_NIGHT = ITEMS.register("space_night", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.SPACE_NIGHT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND = ITEMS.register("underground", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> ALT_UNDERGROUND = ITEMS.register("alt_underground", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.ALT_UNDERGROUND), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> MUSHROOMS = ITEMS.register("mushrooms", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.MUSHROOMS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> JUNGLE = ITEMS.register("jungle", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.JUNGLE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> JUNGLE_NIGHT = ITEMS.register("jungle_night", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.JUNGLE_NIGHT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND_JUNGLE = ITEMS.register("underground_jungle", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND_JUNGLE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> CORRUPTION = ITEMS.register("corruption", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.CORRUPTION), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND_CORRUPTION = ITEMS.register("underground_corruption", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND_CORRUPTION), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> CRIMSON = ITEMS.register("crimson", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.CRIMSON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND_CRIMSON = ITEMS.register("underground_crimson", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND_CRIMSON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> THE_HALLOW = ITEMS.register("the_hallow", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.THE_HALLOW), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERGROUND_HALLOW = ITEMS.register("underground_hallow", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERGROUND_HALLOW), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> UNDERWORLD = ITEMS.register("underworld", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.UNDERWORLD), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> DUNGEON = ITEMS.register("dungeon", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.DUNGEON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> TEMPLE = ITEMS.register("temple", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.TEMPLE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> AETHER = ITEMS.register("aether", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.AETHER), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> GRAVEYARD = ITEMS.register("graveyard", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.GRAVEYARD), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> TOWN_DAY = ITEMS.register("town_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.TOWN_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> TOWN_NIGHT = ITEMS.register("town_night", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.TOWN_NIGHT), ModRarity.EXPERT));

    public static final DeferredItem<CustomRarityItem> BOSS_1 = ITEMS.register("boss_1", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.BOSS_1), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> BOSS_2 = ITEMS.register("boss_2", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.BOSS_2), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> BOSS_3 = ITEMS.register("boss_3", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.BOSS_3), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> BOSS_4 = ITEMS.register("boss_4", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.BOSS_4), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> BOSS_5 = ITEMS.register("boss_5", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.BOSS_5), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> DEERCLOPS = ITEMS.register("deerclops", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.DEERCLOPS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> QUEEN_SLIME = ITEMS.register("queen_slime", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.QUEEN_SLIME), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> PLANTERA = ITEMS.register("plantera", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.PLANTERA), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> EMPRESS_OF_LIGHT = ITEMS.register("empress_of_light", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.EMPRESS_OF_LIGHT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> DUKE_FISHRON = ITEMS.register("duke_fishron", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.DUKE_FISHRON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> MOON_LORD = ITEMS.register("moon_lord", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.MOON_LORD), ModRarity.EXPERT));

    public static final DeferredItem<CustomRarityItem> EERIE = ITEMS.register("eerie", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.EERIE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> ECLIPSE = ITEMS.register("eclipse", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.ECLIPSE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> GOBLIN_ARMY = ITEMS.register("goblin_army", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.GOBLIN_ARMY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> PIRATE_INVASION = ITEMS.register("pirate_invasion", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.PIRATE_INVASION), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> MARTIAN_MADNESS = ITEMS.register("martian_madness", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.MARTIAN_MADNESS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> PUMPKIN_MOON = ITEMS.register("pumpkin_moon", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.PUMPKIN_MOON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> FROST_MOON = ITEMS.register("frost_moon", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.FROST_MOON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> THE_TOWERS = ITEMS.register("the_towers", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.THE_TOWERS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> SANDSTORM = ITEMS.register("sandstorm", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.SANDSTORM), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OLD_ONES_ARMY = ITEMS.register("old_ones_army", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OLD_ONES_ARMY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> SLIME_RAIN = ITEMS.register("slime_rain", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.SLIME_RAIN), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> WINDY_DAY = ITEMS.register("windy_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.WINDY_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> RAIN = ITEMS.register("rain", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.RAIN), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> MORNING_RAIN = ITEMS.register("morning_rain", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.MORNING_RAIN), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> STORM = ITEMS.register("storm", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.STORM), ModRarity.EXPERT));

    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_RAIN = ITEMS.register("otherworldly_rain", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_RAIN), ModRarity.COMMON));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_OVERWORLD_DAY = ITEMS.register("otherworldly_overworld_day", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_OVERWORLD_DAY), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_NIGHT = ITEMS.register("otherworldly_night", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_NIGHT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_UNDERGROUND = ITEMS.register("otherworldly_underground", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_UNDERGROUND), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_DESERT = ITEMS.register("otherworldly_desert", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_DESERT), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_OCEAN = ITEMS.register("otherworldly_ocean", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_OCEAN), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_MUSHROOMS = ITEMS.register("otherworldly_mushrooms", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_MUSHROOMS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_JUNGLE = ITEMS.register("otherworldly_jungle", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_JUNGLE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_DUNGEON = ITEMS.register("otherworldly_dungeon", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_DUNGEON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_SPACE = ITEMS.register("otherworldly_space", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_SPACE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_ICE = ITEMS.register("otherworldly_ice", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_ICE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_UNDERWORLD = ITEMS.register("otherworldly_underworld", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_UNDERWORLD), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_SNOW = ITEMS.register("otherworldly_snow", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_SNOW), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_CORRUPTION = ITEMS.register("otherworldly_corruption", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_CORRUPTION), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_UNDERGROUND_CORRUPTION = ITEMS.register("otherworldly_underground_corruption", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_UNDERGROUND_CORRUPTION), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_CRIMSON = ITEMS.register("otherworldly_crimson", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_CRIMSON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_UNDERGROUND_CRIMSON = ITEMS.register("otherworldly_underground_crimson", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_UNDERGROUND_CRIMSON), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_HALLOW = ITEMS.register("otherworldly_hallow", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_HALLOW), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_UNDERGROUND_HALLOW = ITEMS.register("otherworldly_underground_hallow", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_UNDERGROUND_HALLOW), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_EERIE = ITEMS.register("otherworldly_eerie", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_EERIE), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_BOSS_1 = ITEMS.register("otherworldly_boss_1", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_BOSS_1), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_BOSS_2 = ITEMS.register("otherworldly_boss_2", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_BOSS_2), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_INVASION = ITEMS.register("otherworldly_invasion", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_INVASION), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_THE_TOWERS = ITEMS.register("otherworldly_the_towers", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_THE_TOWERS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_LUNAR_BOSS = ITEMS.register("otherworldly_lunar_boss", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_LUNAR_BOSS), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_PLANTERA = ITEMS.register("otherworldly_plantera", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_PLANTERA), ModRarity.EXPERT));
    public static final DeferredItem<CustomRarityItem> OTHERWORLDLY_WALL_OF_FLESH = ITEMS.register("otherworldly_wall_of_flesh", () -> new CustomRarityItem(new Item.Properties().stacksTo(1).fireResistant().jukeboxPlayable(CMJukeboxSongs.OTHERWORLDLY_WALL_OF_FLESH), ModRarity.EXPERT));
}
