package org.confluence.music.common.init;

import net.minecraft.Util;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.item.JukeboxSong;
import org.confluence.music.ConfluenceMusic;

public final class CMJukeboxSongs {
    public static final ResourceKey<JukeboxSong> ALPHA = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("alpha"));
    public static final ResourceKey<JukeboxSong> NEW_JOURNEY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("new_journey"));
    public static final ResourceKey<JukeboxSong> OVERWORLD_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("overworld_day"));
    public static final ResourceKey<JukeboxSong> ALT_OVERWORLD_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("alt_overworld_day"));
    public static final ResourceKey<JukeboxSong> OVERWORLD_NIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("overworld_night"));
    public static final ResourceKey<JukeboxSong> JOURNEYS_BEGINNING = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("journeys_beginning"));
    public static final ResourceKey<JukeboxSong> JOURNEYS_END = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("journeys_end"));
    public static final ResourceKey<JukeboxSong> TITLE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("title"));
    public static final ResourceKey<JukeboxSong> ALT_TITLE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("alt_title"));
    public static final ResourceKey<JukeboxSong> DAY_REMIX = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("day_remix"));
    public static final ResourceKey<JukeboxSong> SNOW = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("snow"));
    public static final ResourceKey<JukeboxSong> ICE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("ice"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND_ICE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground_ice"));
    public static final ResourceKey<JukeboxSong> DESERT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("desert"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND_DESERT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground_desert"));
    public static final ResourceKey<JukeboxSong> OCEAN_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("ocean_day"));
    public static final ResourceKey<JukeboxSong> OCEAN_NIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("ocean_night"));
    public static final ResourceKey<JukeboxSong> SPACE_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("space_day"));
    public static final ResourceKey<JukeboxSong> SPACE_NIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("space_night"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground"));
    public static final ResourceKey<JukeboxSong> ALT_UNDERGROUND = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("alt_underground"));
    public static final ResourceKey<JukeboxSong> MUSHROOMS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("mushrooms"));
    public static final ResourceKey<JukeboxSong> JUNGLE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("jungle"));
    public static final ResourceKey<JukeboxSong> JUNGLE_NIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("jungle_night"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND_JUNGLE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground_jungle"));
    public static final ResourceKey<JukeboxSong> CORRUPTION = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("corruption"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND_CORRUPTION = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground_corruption"));
    public static final ResourceKey<JukeboxSong> CRIMSON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("crimson"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND_CRIMSON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground_crimson"));
    public static final ResourceKey<JukeboxSong> THE_HALLOW = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("the_hallow"));
    public static final ResourceKey<JukeboxSong> UNDERGROUND_HALLOW = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underground_hallow"));
    public static final ResourceKey<JukeboxSong> UNDERWORLD = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("underworld"));
    public static final ResourceKey<JukeboxSong> DUNGEON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("dungeon"));
    public static final ResourceKey<JukeboxSong> TEMPLE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("temple"));
    public static final ResourceKey<JukeboxSong> AETHER = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("aether"));
    public static final ResourceKey<JukeboxSong> GRAVEYARD = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("graveyard"));
    public static final ResourceKey<JukeboxSong> TOWN_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("town_day"));
    public static final ResourceKey<JukeboxSong> TOWN_NIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("town_night"));
    public static final ResourceKey<JukeboxSong> BOSS_1 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("boss_1"));
    public static final ResourceKey<JukeboxSong> BOSS_2 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("boss_2"));
    public static final ResourceKey<JukeboxSong> BOSS_3 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("boss_3"));
    public static final ResourceKey<JukeboxSong> BOSS_4 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("boss_4"));
    public static final ResourceKey<JukeboxSong> BOSS_5 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("boss_5"));
    public static final ResourceKey<JukeboxSong> DEERCLOPS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("deerclops"));
    public static final ResourceKey<JukeboxSong> QUEEN_SLIME = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("queen_slime"));
    public static final ResourceKey<JukeboxSong> PLANTERA = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("plantera"));
    public static final ResourceKey<JukeboxSong> EMPRESS_OF_LIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("empress_of_light"));
    public static final ResourceKey<JukeboxSong> DUKE_FISHRON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("duke_fishron"));
    public static final ResourceKey<JukeboxSong> MOON_LORD = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("moon_lord"));
    public static final ResourceKey<JukeboxSong> EERIE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("eerie"));
    public static final ResourceKey<JukeboxSong> ECLIPSE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("eclipse"));
    public static final ResourceKey<JukeboxSong> GOBLIN_ARMY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("goblin_army"));
    public static final ResourceKey<JukeboxSong> PIRATE_INVASION = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("pirate_invasion"));
    public static final ResourceKey<JukeboxSong> MARTIAN_MADNESS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("martian_madness"));
    public static final ResourceKey<JukeboxSong> PUMPKIN_MOON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("pumpkin_moon"));
    public static final ResourceKey<JukeboxSong> FROST_MOON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("frost_moon"));
    public static final ResourceKey<JukeboxSong> THE_TOWERS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("the_towers"));
    public static final ResourceKey<JukeboxSong> SANDSTORM = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("sandstorm"));
    public static final ResourceKey<JukeboxSong> OLD_ONES_ARMY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("old_ones_army"));
    public static final ResourceKey<JukeboxSong> SLIME_RAIN = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("slime_rain"));
    public static final ResourceKey<JukeboxSong> WINDY_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("windy_day"));
    public static final ResourceKey<JukeboxSong> RAIN = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("rain"));
    public static final ResourceKey<JukeboxSong> MORNING_RAIN = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("morning_rain"));
    public static final ResourceKey<JukeboxSong> STORM = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("storm"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_RAIN = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_rain"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_OVERWORLD_DAY = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_overworld_day"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_NIGHT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_night"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_UNDERGROUND = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_underground"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_DESERT = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_desert"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_OCEAN = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_ocean"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_MUSHROOMS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_mushrooms"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_JUNGLE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_jungle"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_DUNGEON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_dungeon"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_SPACE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_space"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_ICE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_ice"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_UNDERWORLD = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_underworld"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_SNOW = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_snow"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_CORRUPTION = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_corruption"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_UNDERGROUND_CORRUPTION = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_underground_corruption"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_CRIMSON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_crimson"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_UNDERGROUND_CRIMSON = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_underground_crimson"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_HALLOW = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_hallow"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_UNDERGROUND_HALLOW = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_underground_hallow"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_EERIE = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_eerie"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_BOSS_1 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_boss_1"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_BOSS_2 = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_boss_2"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_INVASION = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_invasion"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_THE_TOWERS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_the_towers"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_LUNAR_BOSS = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_lunar_boss"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_PLANTERA = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_plantera"));
    public static final ResourceKey<JukeboxSong> OTHERWORLDLY_WALL_OF_FLESH = ResourceKey.create(Registries.JUKEBOX_SONG, ConfluenceMusic.asResource("otherworldly_wall_of_flesh"));

    public static void boostrap(BootstrapContext<JukeboxSong> context) {
        register(context, ALPHA, SoundEvents.MUSIC_CREDITS, 603.0F, 0);
        register(context, NEW_JOURNEY, CMSoundEvents.NEW_JOURNEY, 1, 1);
        register(context, OVERWORLD_DAY, CMSoundEvents.OVERWORLD_DAY, 1, 1);
        register(context, ALT_OVERWORLD_DAY, CMSoundEvents.ALT_OVERWORLD_DAY, 1, 1);
        register(context, OVERWORLD_NIGHT, CMSoundEvents.OVERWORLD_NIGHT, 1, 1);
        register(context, JOURNEYS_BEGINNING, CMSoundEvents.JOURNEYS_BEGINNING, 1, 1);
        register(context, JOURNEYS_END, CMSoundEvents.JOURNEYS_END, 1, 1);
        register(context, TITLE, CMSoundEvents.TITLE, 1, 1);
        register(context, ALT_TITLE, CMSoundEvents.ALT_TITLE, 1, 1);
        register(context, DAY_REMIX, CMSoundEvents.DAY_REMIX, 1, 1);
        register(context, SNOW, CMSoundEvents.SNOW, 1, 1);
        register(context, ICE, CMSoundEvents.ICE, 1, 1);
        register(context, UNDERGROUND_ICE, CMSoundEvents.UNDERGROUND_ICE, 1, 1);
        register(context, DESERT, CMSoundEvents.DESERT, 1, 1);
        register(context, UNDERGROUND_DESERT, CMSoundEvents.UNDERGROUND_DESERT, 1, 1);
        register(context, OCEAN_DAY, CMSoundEvents.OCEAN_DAY, 1, 1);
        register(context, OCEAN_NIGHT, CMSoundEvents.OCEAN_NIGHT, 1, 1);
        register(context, SPACE_DAY, CMSoundEvents.SPACE_DAY, 1, 1);
        register(context, SPACE_NIGHT, CMSoundEvents.SPACE_NIGHT, 1, 1);
        register(context, UNDERGROUND, CMSoundEvents.UNDERGROUND, 1, 1);
        register(context, ALT_UNDERGROUND, CMSoundEvents.ALT_UNDERGROUND, 1, 1);
        register(context, MUSHROOMS, CMSoundEvents.MUSHROOMS, 1, 1);
        register(context, JUNGLE, CMSoundEvents.JUNGLE, 1, 1);
        register(context, JUNGLE_NIGHT, CMSoundEvents.JUNGLE_NIGHT, 1, 1);
        register(context, UNDERGROUND_JUNGLE, CMSoundEvents.UNDERGROUND_JUNGLE, 1, 1);
        register(context, CORRUPTION, CMSoundEvents.CORRUPTION, 1, 1);
        register(context, UNDERGROUND_CORRUPTION, CMSoundEvents.UNDERGROUND_CORRUPTION, 1, 1);
        register(context, CRIMSON, CMSoundEvents.CRIMSON, 1, 1);
        register(context, UNDERGROUND_CRIMSON, CMSoundEvents.UNDERGROUND_CRIMSON, 1, 1);
        register(context, THE_HALLOW, CMSoundEvents.THE_HALLOW, 1, 1);
        register(context, UNDERGROUND_HALLOW, CMSoundEvents.UNDERGROUND_HALLOW, 1, 1);
        register(context, UNDERWORLD, CMSoundEvents.UNDERWORLD, 1, 1);
        register(context, DUNGEON, CMSoundEvents.DUNGEON_FLOOR_1, 1, 1);
        register(context, TEMPLE, CMSoundEvents.TEMPLE, 1, 1);
        register(context, AETHER, CMSoundEvents.AETHER, 1, 1);
        register(context, GRAVEYARD, CMSoundEvents.GRAVEYARD, 1, 1);
        register(context, TOWN_DAY, CMSoundEvents.TOWN_DAY, 1, 1);
        register(context, TOWN_NIGHT, CMSoundEvents.TOWN_NIGHT, 1, 1);
        register(context, BOSS_1, CMSoundEvents.BOSS_1, 1, 1);
        register(context, BOSS_2, CMSoundEvents.BOSS_2, 1, 1);
        register(context, BOSS_3, CMSoundEvents.BOSS_3, 1, 1);
        register(context, BOSS_4, CMSoundEvents.BOSS_4, 1, 1);
        register(context, BOSS_5, CMSoundEvents.BOSS_5, 1, 1);
        register(context, DEERCLOPS, CMSoundEvents.DEERCLOPS, 1, 1);
        register(context, QUEEN_SLIME, CMSoundEvents.QUEEN_SLIME, 1, 1);
        register(context, PLANTERA, CMSoundEvents.PLANTERA, 1, 1);
        register(context, EMPRESS_OF_LIGHT, CMSoundEvents.EMPRESS_OF_LIGHT, 1, 1);
        register(context, DUKE_FISHRON, CMSoundEvents.DUKE_FISHRON, 1, 1);
        register(context, MOON_LORD, CMSoundEvents.MOON_LORD, 1, 1);
        register(context, EERIE, CMSoundEvents.EERIE, 1, 1);
        register(context, ECLIPSE, CMSoundEvents.ECLIPSE, 1, 1);
        register(context, GOBLIN_ARMY, CMSoundEvents.GOBLIN_ARMY, 1, 1);
        register(context, PIRATE_INVASION, CMSoundEvents.PIRATE_INVASION, 1, 1);
        register(context, MARTIAN_MADNESS, CMSoundEvents.MARTIAN_MADNESS, 1, 1);
        register(context, PUMPKIN_MOON, CMSoundEvents.PUMPKIN_MOON, 1, 1);
        register(context, FROST_MOON, CMSoundEvents.FROST_MOON, 1, 1);
        register(context, THE_TOWERS, CMSoundEvents.THE_TOWERS, 1, 1);
        register(context, SANDSTORM, CMSoundEvents.SANDSTORM, 1, 1);
        register(context, OLD_ONES_ARMY, CMSoundEvents.OLD_ONES_ARMY, 1, 1);
        register(context, SLIME_RAIN, CMSoundEvents.SLIME_RAIN, 1, 1);
        register(context, WINDY_DAY, CMSoundEvents.WINDY_DAY, 1, 1);
        register(context, RAIN, CMSoundEvents.RAIN, 1, 1);
        register(context, MORNING_RAIN, CMSoundEvents.MORNING_RAIN, 1, 1);
        register(context, STORM, CMSoundEvents.STORM, 1, 1);
        register(context, OTHERWORLDLY_RAIN, CMSoundEvents.OTHERWORLDLY_RAIN, 1, 1);
        register(context, OTHERWORLDLY_OVERWORLD_DAY, CMSoundEvents.OTHERWORLDLY_OVERWORLD_DAY, 1, 1);
        register(context, OTHERWORLDLY_NIGHT, CMSoundEvents.OTHERWORLDLY_NIGHT, 1, 1);
        register(context, OTHERWORLDLY_UNDERGROUND, CMSoundEvents.OTHERWORLDLY_UNDERGROUND, 1, 1);
        register(context, OTHERWORLDLY_DESERT, CMSoundEvents.OTHERWORLDLY_DESERT, 1, 1);
        register(context, OTHERWORLDLY_OCEAN, CMSoundEvents.OTHERWORLDLY_OCEAN, 1, 1);
        register(context, OTHERWORLDLY_MUSHROOMS, CMSoundEvents.OTHERWORLDLY_MUSHROOMS, 1, 1);
        register(context, OTHERWORLDLY_JUNGLE, CMSoundEvents.OTHERWORLDLY_JUNGLE, 1, 1);
        register(context, OTHERWORLDLY_DUNGEON, CMSoundEvents.OTHERWORLDLY_DUNGEON, 1, 1);
        register(context, OTHERWORLDLY_SPACE, CMSoundEvents.OTHERWORLDLY_SPACE, 1, 1);
        register(context, OTHERWORLDLY_UNDERWORLD, CMSoundEvents.OTHERWORLDLY_UNDERWORLD, 1, 1);
        register(context, OTHERWORLDLY_SNOW, CMSoundEvents.OTHERWORLDLY_SNOW, 1, 1);
        register(context, OTHERWORLDLY_ICE, CMSoundEvents.OTHERWORLDLY_ICE, 1, 1);
        register(context, OTHERWORLDLY_CORRUPTION, CMSoundEvents.OTHERWORLDLY_CORRUPTION, 1, 1);
        register(context, OTHERWORLDLY_UNDERGROUND_CORRUPTION, CMSoundEvents.OTHERWORLDLY_UNDERGROUND_CORRUPTION, 1, 1);
        register(context, OTHERWORLDLY_CRIMSON, CMSoundEvents.OTHERWORLDLY_CRIMSON, 1, 1);
        register(context, OTHERWORLDLY_UNDERGROUND_CRIMSON, CMSoundEvents.OTHERWORLDLY_UNDERGROUND_CRIMSON, 1, 1);
        register(context, OTHERWORLDLY_HALLOW, CMSoundEvents.OTHERWORLDLY_HALLOW, 1, 1);
        register(context, OTHERWORLDLY_UNDERGROUND_HALLOW, CMSoundEvents.OTHERWORLDLY_UNDERGROUND_HALLOW, 1, 1);
        register(context, OTHERWORLDLY_EERIE, CMSoundEvents.OTHERWORLDLY_EERIE, 1, 1);
        register(context, OTHERWORLDLY_BOSS_1, CMSoundEvents.OTHERWORLDLY_BOSS_1, 1, 1);
        register(context, OTHERWORLDLY_BOSS_2, CMSoundEvents.OTHERWORLDLY_BOSS_2, 1, 1);
        register(context, OTHERWORLDLY_INVASION, CMSoundEvents.OTHERWORLDLY_INVASION, 1, 1);
        register(context, OTHERWORLDLY_THE_TOWERS, CMSoundEvents.OTHERWORLDLY_THE_TOWERS, 1, 1);
        register(context, OTHERWORLDLY_LUNAR_BOSS, CMSoundEvents.OTHERWORLDLY_LUNAR_BOSS, 1, 1);
        register(context, OTHERWORLDLY_PLANTERA, CMSoundEvents.OTHERWORLDLY_PLANTERA, 1, 1);
        register(context, OTHERWORLDLY_WALL_OF_FLESH, CMSoundEvents.OTHERWORLDLY_WALL_OF_FLESH, 1, 1);
    }

    private static void register(BootstrapContext<JukeboxSong> context, ResourceKey<JukeboxSong> key, Holder<SoundEvent> soundEvent, float lengthInSeconds, int comparatorOutput) {
        context.register(key, new JukeboxSong(soundEvent, Component.translatable(Util.makeDescriptionId("jukebox_song", key.location())), lengthInSeconds, comparatorOutput));
    }
}
